- hosts: all
  gather_facts: yes
  remote_user: root

  tasks:
    - name: Install packages for
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: Run readmine container
      community.docker.docker_container:
        name: redmine
        image: redmine:4.2.2
        restart_policy: always
        pull: yes
        restart: yes
        published_ports: "{{ app_port }}:3000"
        container_default_behavior: compatibility
